version: '3.8'

networks:
  postgres-net:
    name: postgres-net

volumes:
  postgres-vol:

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: locacao_veiculo
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-net

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "yuriluiz557@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - 8081:80
    networks:
      - postgres-net






